Updated requirements
lgiordani/cookiecutter-pypackage pull request #2
Opened 2018-09-17 15:16 UTC by IgnatiusFlo

This PR updates some requirements.
This solves #1

2018-09-17 15:19 UTC, lgiordani requested changes

2018-09-17 15:19 UTC, lgiordani commented on {{cookiecutter.project_slug}}/requirements/test.txt
>  pytest-cov==2.4.0{%- endif %}
I guess at this point it might be worth updating pytest-cov as weel. Do you have time to test it please? :penguin:

2018-09-17 15:19 UTC, lgiordani commented on {{cookiecutter.project_slug}}/requirements/dev.txt
> +punch.py >=1.5
Can you please get rid of the spaces? Just for consistency :tulip:

2018-09-17 15:38 UTC, lgiordani commented
Thanks, give me some days to test that the new packages work as intended and then we can merge! :1st_place_medal:

2018-09-24 08:32 UTC, IgnatiusFlo commented
Hello Leonardo, I was going over this with a programmer friend of mine and we got Travis to build when we took out python 3.3 from the Tox file. I don't know if that's something of interest. Would you like me to make that change?

2018-09-24 08:46 UTC, lgiordani commented
Hi Kate! Yes, Python 3.3 is not supported anymore, feel free to remove it from the Tox file and see if it passes the tests. By the way I tested the new requirements and they work, but I was thinking that maybe we might drop the versions completely, as this is a template and people might want to decide if to freeze the requirements or not. What do you think?

2018-09-24 11:37 UTC, IgnatiusFlo commented
Okay. I'm not sure how to make that happen. So this is the build...  https://github.com/IgnatiusFlo/cookiecutter-pypackage/pull/2/checks?check_run_id=18998569
We faffed around adding and subtracting python versions.  Should/can I just push that commit to you from in Github? If not I can't make a pull request till tomorrow because I'm at work and then busy, but I will. (I've just seen you added 3.6 support, I could add that back in).

Idk, looking at your PyPi page and the Gitter thread, looks like you have many options out there for users, for a multitude of projects. If this is the vanilla cookie, if you will, what do you want to offer, as the standard 'ultimate Python package project template'?

2018-09-24 11:52 UTC, lgiordani commented
The standard way to do it is to send a pull request, yes. Create a branch with just that change and send the PR. If you want to add Python 3.6 and 3.7 in the same PR they are more than welcome.

I'm not sure I understood the rest of the message, sorry!

2018-09-24 13:51 UTC, IgnatiusFlo commented
Okay. I'll do that soon as I can.

Forgive me, I'm probably not following you. Where you say '**as this is a template and people might want to decide if to freeze the requirements or not**'. Is that usual for a template? I looked through some of the other kinds of cookiecutter and some do, some don't. If this is the standard original version would it be better to have updated versions in the background because this is the first one people would use? Have you had feedback from users asking for such a change?

2018-09-24 14:44 UTC, lgiordani commented
I see now, sorry for not understanding before. This is not the original cookiecutter template by Audrey, it is just a modification that uses different packages (`punch` instead of `bumpversion`) and structure (the `requirements` directory). Actually I don't know who is using this template, apart from me :stuck_out_tongue: 

Not freezing the versions (i.e. just listing the package names) means that when you run `pip install` you will get the latest version of all the packages mentioned in the requirements, and I was thinking that maybe this is the most generic thing that we can provide. Then, if someone has a specific requirement because of compatibility issues, they may freeze the version adding `==some_number` in the requirement files. Does this make sense?

2018-09-24 15:51 UTC, IgnatiusFlo commented
Yes! Perfect sense. If no version spec at all is the most economic and least perscriptive way to go about it then yes, that sounds like a plan.

2018-09-24 15:55 UTC, IgnatiusFlo commented
So, the files we changed before in the slug and the requirements_dev.txt?

2018-09-24 16:16 UTC, lgiordani commented
Yes `{{cookiecutter.project_slug}}/requirements/test.txt` and `{{cookiecutter.project_slug}}/requirements/dev.txt`. This is for this PR.

`.travis.yml`, `tox.ini`, `{{cookiecutter.project_slug}}/.travis.yml`, and `{{cookiecutter.project_slug}}/tox.ini` for the other PR.

2018-09-30 12:20 UTC, IgnatiusFlo commented
I thought I had pushed the right things to the right place, but now it builds and I expected it not to. Did unfreezing fix the problem?

2018-10-01 14:00 UTC, lgiordani requested changes

2018-10-01 14:00 UTC, lgiordani commented on {{cookiecutter.project_slug}}/requirements.txt
> --r requirements/prod.txt
I'd prefer to leave this file here, it is a good shortcut for people used to just run `pip install -r requirements`

2018-10-01 14:01 UTC, lgiordani commented
It's almost done! The above comment is the only thing to change :wink: We discussed removing the `requirements_dev.txt` and not the `requirements.txt`. Many people are used to just `pip install -r requirements.txt`, so I'd leave it there

2018-11-12 17:58 UTC, lgiordani commented
Hi! What happened with this PR? Are you still working on it? The tests are failing, are you stuck?

2018-11-17 17:26 UTC, lgiordani commented
See the other PR that you submitted. Since it seems work has been stopped on this I borrowed your code and created another branch, merged in #5. So thanks for your work anyway, it was very helpful!

2018-11-17 17:26 UTC, closed without merging