Travis happy build
lgiordani/cookiecutter-pypackage pull request #3
Opened 2018-09-25 19:41 UTC by IgnatiusFlo

Hello,

When I added py3.6 it wouldn't build so I made a branch with the commit that worked. It made Travis have an issue with unacceptable characters in paths. On Pypi it says Py3.6 is supported and I don't know why this is happening. 

There is a mention in setup.py about versions. Maybe.... :bug:

2018-09-26 13:45 UTC, lgiordani commented
Hi, this PR is good, can you just remove the changes in the requirements? They are part of another PR. To do it you can just `git checkout origin/master filename` on those files and commit. Let me know if you have issues.

May you send another PR with the 3.6 change, even if it doesn't pass the tests? We can discuss the code there. Thanks

2018-09-26 13:47 UTC, lgiordani requested changes

2018-09-26 13:47 UTC, lgiordani commented on {{cookiecutter.project_slug}}/requirements/dev.txt
>  -r test.txt
Please get rid of these changes, we can put them in the other PR :beach_umbrella:

2018-09-26 13:47 UTC, lgiordani commented on {{cookiecutter.project_slug}}/requirements/test.txt
>  -r prod.txt
These as well :penguin:

2018-09-26 14:45 UTC, IgnatiusFlo commented
I was going to add 3.6 to the setup.py classifiers and then add it back into the tox and travis files because I think that will work, but I will do as you ask.  

I didn't mean the requirements.txt changes to be in this PR. Thanks for your patience while I figure this out. I will get back to you at the weekend. :sunflower:

2018-09-26 14:49 UTC, lgiordani commented
Kate, no worries at all. Thank you for helping!

2018-11-12 17:56 UTC, lgiordani commented
Hi! What happened with this PR? Are you still working on it?

2018-11-17 12:22 UTC, lgiordani commented
Hi! Thanks for the PR, I imported your code in another branch and created #4 You were missing a couple of changes, but apparently you don't have time to work on them so I did it. Thanks a lot for the contribution! :+1:

2018-11-17 12:22 UTC, closed without merging